language: node_js
node_js:
  - "node"
  - "12"
  - "10"
  - "8"
install:
  - npm ci
script:
  - npm test
  - npm run lint-travis

jobs:
  include:
    - stage: "Coverage"
      script:
        - npm run travis-coverage
